<?php require_once './templates/header.phtml'?>
<h1 class="text-center text-violet">Nuestros Categorias son:</h1>


<form method="post" action="addCategoria" class="form-control form-control-sm">
    <div class="mb-3">
        <label for="nombre" class="form-label">Ingrese un nombre de categoria</label>
        <input type="text" class="form-control" name="nombre" id="nombre">
    </div>
    
    <button type="submit" class="btn btn-violet">Agregar</button>
</form>

<ul class="list-group">
    <?php foreach ($list as $item): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <?= $item->nombre_categoria ?>
            <div>
                <a href="editCategoria/<?= $item->id_categoria?>" class="btn btn-warning me-2">Editar</a>
                <a href="removeCategoria/<?= $item->id_categoria?>" class="btn btn-danger">Borrar</a>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
<?php require_once './templates/footer.phtml'?>
