<?php require_once './templates/header.phtml'?>
<h1>Lista de pedidos:</h1>

<form method="post" action="filtrarPedido" class="form-control form-control-sm mb-3">
<div class="row flex-row align-items-center">
    <div class="col-auto">
        <label for="filtroCategoria" class="h5">Filtrar por:</label>
    </div>
    <div class="col-auto">
    <select class="form-select"  name="filtroProducto" id="filtroProducto" >
        <option value="">Todas los productos</option> 
            <?php
            foreach($listOfProducts as $item):?>
                <option value="<?= $item->id?>"><?= $item->nombre_producto?></option>
                <?php endforeach?>
        
                
        </option>
    </select>
    </div>
    <div class="col-auto">
            <button type="submit" class="btn btn-success">Filtrar</button>
    </div> 
</div>
</form>

<table class="table table-striped table-hover" style="background-color: #D09EE7;">
    <thead>
        <th >Producto</th>
        <th >Categoria</th>
        <th >Marca </th>
        <th >Precio </th>
        <th >Unidades</th>
        <th >Monto total    </th>

    </thead>

    <?php
    foreach($list as $item):?>
        <tbody>
            <tr>
            <td><a href="products/<?= $item->id_pedido?>" class="text-decoration-none text-violet"><?= $item->nombre?> </a></td>
                <td><?= $item->nombre_categoria ?></td>
                <td><?= $item->marca?></td> 
                <td><?= $item->precio ?></td> 
                <td><?= $item->unidad?></td> 
                <td><?= $item->monto_total?></td> 
                
            </tr>
        </tbody>
    <?php endforeach?>
    

</table>
    
<?php require_once './templates/footer.phtml'?>